### ISSUE TITLE
_next page is misreported

### ISSUE THREAD

**Issue by sehe** [tracksinspector/papi#1]
A simple list node seems to report the next page as page=2 independent of the current selected page

E.g. using `example/app.py` the url /things?pretty=42&count=1&page=13 responds

```
{
  "_items": [],
  "_self": {
    "href": "/things"
  },
  "_top": {
    "href": "/things"
  },
  "_parent": {
    "href": "/"
  },
  "_next": {
    "href": "/things?page=2"
  },
  "_name": "things"
}
```

**Comment by tdammers** [comment]
https://github.com/tracksinspector/papi/commit/f35948f552e5246fd432b3c46cd84bf5ceb90406 should fix this, and also a bunch of other HATEOAS related issues.
